version: '3.9'

services:
  php:
    build: .
    image: php-emfy:latest
    restart: unless-stopped
    volumes:
      - ".:/var/www/html"
    env_file:
      - "./.env"
  consumer:
    image: php-emfy:latest
    restart: unless-stopped
    volumes:
      - ".:/var/www/html"
    working_dir: '/var/www/html'
    command: [ 'php', 'vendor/bin/laminas', 'system:consumer', '-tcrm' ]
    env_file:
      - "./.env"
  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    volumes:
      - "./public:/var/www/html/public"
      - "./docker/nginx/conf.d:/etc/nginx/conf.d"
    ports:
      - "8080:80"
    depends_on:
      - php
  mysql:
    image: mysql:8
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 222222
      MYSQL_DATABASE: app
      MYSQL_USER: admin
      MYSQL_PASSWORD: 111111
    volumes:
      - "./dbdata:/var/lib/mysql/"
  beanstalk:
    image: bodsch/docker-beanstalkd:1.10
    ports:
      - "11300:11300"